--- #YAML:1.0
name:               App-Slaughter
version:            3.0.0
abstract:           The Slaughter System Administration Utility.
author:
    - Steve Kemp <steve@steve.org.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:  0
    File::Find:      0
    File::Path:      0
    File::Spec:      0
    File::Temp:      0
    Getopt::Long:    0
    LWP::UserAgent:  0
    perl:            5.008
    Pod::Usage:      0
    POSIX:           0
    Text::Template:  0
resources:
    bugtracker:  https://github.com/skx/slaughter/issues
    GitMirror:   http://git.steve.org.uk/skx/slaughter
    homepage:    https://github.com/skx/slaughter/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/skx/slaughter.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
